#!/usr/bin/env python3
"""
build_catalog.py — the choosing surface for the canon.

Ten measured templates that nothing could reach were worth nothing. This writes
the two files that make them findable:

  wpp-es-html-deck/canon/CATALOG.md    what the model reads to choose.
  wpp-es-html-deck/canon/catalog.json  the machine twin, for lints and tooling.

`useWhen` is the column that matters and the only field written by hand. It says
what PROBLEM the template solves. Everything else — family, form, arity, ground,
density — is a filter you apply after you already know what you are looking for.
Generating useWhen from the other fields produces "three columns, dot headers",
which is what the old SNIPPET-INDEX descriptions are and why they never helped
anyone choose.

  python3 authoring/canon-tools/build_catalog.py --write
  python3 authoring/canon-tools/build_catalog.py --check    # CI: fail if stale

The catalogue has a hard token ceiling. It is loaded on every deck, so it can
never become the thing it replaced — a 5,600-character index nobody reads.
"""
import argparse, json, os, sys

# These tools moved out of the skill (wpp-es-html-deck/canon/_tools/) when the
# skill folder had to fit claude.ai's 200-entry cap. The SOURCES they read moved
# with them; the ARTIFACTS they generate still land inside the skill.
#   authoring/canon-src/<id>/{meta,spec,measure}.json, ref.png, preview.png
#   wpp-es-html-deck/canon/{CATALOG.md, catalog.json, PREVIEWS.png, templates/}
HERE = os.path.dirname(os.path.abspath(__file__))
AUTHORING = os.path.dirname(HERE)
REPO = os.path.dirname(AUTHORING)
SKILL = os.path.join(REPO, "wpp-es-html-deck")
SRC = os.path.join(AUTHORING, "canon-src")
CANON = os.path.join(SKILL, "canon")
TEMPLATES = os.path.join(CANON, "templates")
MD_PATH = os.path.join(CANON, "CATALOG.md")
JSON_PATH = os.path.join(CANON, "catalog.json")

# Loaded every deck. If this is ever hit, the fix is fewer templates or shorter
# useWhen lines — never a bigger ceiling.
TOKEN_CEILING = 1600

FAMILIES = ["A-narrative", "B-enumeration", "C-sequence", "D-quantitative",
            "E-comparison", "F-relational", "G-media", "H-entities", "structural"]


def load():
    out = []
    for d in sorted(os.listdir(SRC)):
        p = os.path.join(SRC, d, "meta.json")
        if d.startswith("_") or not os.path.isfile(p):
            continue
        m = json.load(open(p, encoding="utf-8"))
        spec_path = os.path.join(SRC, d, "spec.json")
        spec = json.load(open(spec_path, encoding="utf-8")) if os.path.isfile(spec_path) else {}
        m["_approved"] = bool(spec.get("approvedBy"))
        out.append(m)
    return out


def render_md(metas):
    lines = [
        "<!-- GENERATED by authoring/canon-tools/build_catalog.py from each",
        "     authoring/canon-src/<id>/meta.json. DO NOT EDIT — --check fails on drift. -->",
        "",
        "# Canon catalogue",
        "",
        f"{len(metas)} templates, each traced from a real slide in the MAP bank.",
        "Choose on `use when` — the rest is filtering. If a fill looks wrong, compare it",
        "against `PREVIEWS.png` (all 25, labelled) before changing anything.",
        "",
        "`ok` = reviewed against its source and passed the gates, BY MACHINE — no human",
        "has signed these off. Eleven specs carry an `approvalNote` caveat (placeholder",
        "logos, headshots, client screenshots). Read it before a client deck.",
        "",
    ]
    by_fam = {}
    for m in metas:
        by_fam.setdefault(m.get("family", "?"), []).append(m)

    for fam in FAMILIES:
        group = by_fam.get(fam)
        if not group:
            continue
        lines += [f"## {fam}", "",
                  "| id | use when | arity | density | media | ok |",
                  "|---|---|---|---|---|---|"]
        for m in sorted(group, key=lambda x: x["id"]):
            lines.append("| `{id}` | {use} | {ar} | {den} | {med} | {ok} |".format(
                id=m["id"], use=m["useWhen"].replace("|", "/"),
                ar=m.get("arity", "-"), den=m.get("density", "-"),
                med=m.get("mediaRole", "none"),
                ok="yes" if m["_approved"] else "?"))
        lines.append("")

    missing = sorted(set(by_fam) - set(FAMILIES))
    if missing:
        lines += [f"<!-- families not in the closed vocabulary: {missing} -->", ""]

    covered = [f for f in FAMILIES[:8] if by_fam.get(f)]
    gaps = [f for f in FAMILIES[:8] if not by_fam.get(f)]
    lines += ["---", "",
              f"Families covered: {len(covered)}/8."
              + (f" **No template yet for: {', '.join(gaps)}** — for those, use the "
                 f"snippet kit (`references/SNIPPET-INDEX.md`) and say so in the plan."
                 if gaps else ""),
              "", JOB_GAPS]
    return "\n".join(lines).rstrip() + "\n"


# A family being populated does NOT mean the job is covered, and the 8/8 line
# above reads as though it does. These are the slides a real pitch asks for that
# the canon cannot serve — declared as a literal because it is a judgement about
# the bank, not something derivable from the metas. Keep it current: when a
# canon template takes one of these jobs, delete its line.
JOB_GAPS = """**Family coverage is not job coverage.** E-comparison holds two
PRIORITISATION tools and no comparison. Do not stretch a template — fall back to
`variants/` and say which slide fell back:

- **Two states weighed against each other** (current vs future, us vs them) — the
  comp-* pair scores MANY candidates, it does not compare two → `comparison-v1`
- **Dated timeline / roadmap / Gantt** — `seq-phase-columns-4` refuses a drawn
  time axis on purpose → `process-timeline-v3` (swimlanes), `-v2`, `-v4`
- **One hero number** → `stats-*` · **attributed quote at poster size** →
  `statement-quote-v2` · **fee structure or any real table** → `charts-v3`
"""
def render_json(metas):
    return json.dumps({
        "$comment": "Generated by authoring/canon-tools/build_catalog.py. Machine twin of "
                    "CATALOG.md. Read useWhen to choose; filter on the closed "
                    "vocabularies.",
        "count": len(metas),
        "vocabulary": {"family": FAMILIES},
        "templates": [{
            "id": m["id"], "name": m.get("name"), "useWhen": m["useWhen"],
            "family": m.get("family"), "secondaryFamily": m.get("secondaryFamily"),
            "form": m.get("form"), "arity": m.get("arity"),
            "arityRange": m.get("arityRange"), "ground": m.get("ground"),
            "density": m.get("density"), "densityChars": m.get("densityChars"),
            "mediaRole": m.get("mediaRole"), "focalRatio": (m.get("focal") or {}).get("ratio"),
            "source": m.get("source"), "replaces": m.get("replaces"),
            "approved": m["_approved"],
        } for m in sorted(metas, key=lambda x: (x.get("family", ""), x["id"]))],
    }, indent=1, ensure_ascii=False) + "\n"


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--write", action="store_true")
    ap.add_argument("--check", action="store_true")
    args = ap.parse_args()
    if not (args.write or args.check):
        ap.error("pass --write or --check")

    metas = load()
    if not metas:
        sys.exit("no canon templates found — nothing to catalogue")
    md, js = render_md(metas), render_json(metas)

    tokens = len(md) * 10 // 37
    if tokens > TOKEN_CEILING:
        print(f"CATALOG TOO LARGE — ~{tokens} tokens, ceiling {TOKEN_CEILING}.\n"
              f"It is loaded every deck. Shorten the useWhen lines or split the "
              f"catalogue by family; do not raise the ceiling.", file=sys.stderr)
        sys.exit(1)

    if args.write:
        open(MD_PATH, "w", encoding="utf-8").write(md)
        open(JSON_PATH, "w", encoding="utf-8").write(js)
        unapproved = [m["id"] for m in metas if not m["_approved"]]
        print(f"wrote canon/CATALOG.md ({len(md):,} chars, ~{tokens} tokens, "
              f"ceiling {TOKEN_CEILING}) and canon/catalog.json")
        print(f"{len(metas)} templates"
              + (f"; {len(unapproved)} still unapproved: {', '.join(unapproved)}"
                 if unapproved else ""))
        return

    stale = [p for p, t in ((MD_PATH, md), (JSON_PATH, js))
             if not os.path.isfile(p) or open(p, encoding="utf-8").read() != t]
    if stale:
        print("CATALOG STALE — a meta.json changed and these did not follow:",
              file=sys.stderr)
        for p in stale:
            print(f"  {os.path.relpath(p, SKILL)}", file=sys.stderr)
        print("\nRun: python3 authoring/canon-tools/build_catalog.py --write", file=sys.stderr)
        sys.exit(1)
    print(f"CATALOG OK — {len(metas)} templates, ~{tokens} tokens")


if __name__ == "__main__":
    main()
