#!/usr/bin/env python3
"""
build_docs.py — one source, two documents, one check.

The design guideline exists three times: references/sections/ (the source),
references/WPP-ES-DESIGN-GUIDELINE.md (all of it in one file) and
references/CORE.md (the always-loaded subset). Nothing kept them in step, and
the drift is silent because all three read plausibly on their own.

That is not hypothetical. The frame-constants commit edited CORE §2 and §12.15a
and left sections/ behind within the hour, in a repo whose own notes flag the
triplication as a standing hazard. Anyone can do it; nobody notices.

So: sections/ is the ONLY file anyone edits. This script emits the other two and
`--check` fails when either has drifted.

  python3 scripts/build_docs.py --write     # regenerate both
  python3 scripts/build_docs.py --check     # fail (exit 1) if either is stale

CORE is a SUBSET, selected by heading in the manifest below, and every CORE
heading must exist verbatim in sections/ — 47 of its 48 already did. The odd one
out is a wrapper CORE adds around the hoisted composition subsections, and it is
declared here rather than hidden in the text.

WHY THE MASTER IS ALSO GENERATED, when only CORE is loaded per deck: a --check
that covers CORE but not the master proves the wrong half. The next edit to a
section drifts the master instead, and the triplication returns wearing a gate.
The master goes to build/ (gitignored) with a stub left at the old path, because
it is the only single-file form a human reviewer or a diff against a future
playbook can use.
"""
import argparse, os, re, sys

HERE = os.path.dirname(os.path.abspath(__file__))
SKILL = os.path.dirname(HERE)
SECTIONS = os.path.join(SKILL, "references", "sections")
CORE_PATH = os.path.join(SKILL, "references", "CORE.md")
MASTER_PATH = os.path.join(SKILL, "build", "WPP-ES-DESIGN-GUIDELINE.md")

BANNER = ("<!-- GENERATED by scripts/build_docs.py from references/sections/. "
          "DO NOT EDIT — `build_docs.py --check` fails on drift and your edit "
          "is lost on the next --write. Edit the section file instead. -->\n\n")

# Declared, not inherited. CORE's framing prose is content too, so it lives here
# rather than being silently regenerated away.
#
# What is deliberately ABSENT: the old closing paragraph naming
# WPP-ES-DESIGN-GUIDELINE.md as "still the master" and ranking CORE below it.
# That sentence invited a 28,645-token read to settle questions CORE already
# answers, and it is no longer even true — sections/ is the source and the
# master is a build product.
CORE_PREAMBLE = """# WPP ES | MAP — CORE design rules

Everything needed to lay out ANY slide. Read this once per deck, in full.
These are the numbers verify_deck.py enforces.

Content-specific sections are NOT here. Open one from `sections/` only when its
trigger applies:

| Open this | Only when |
|---|---|
| `sections/8-iconography.md` | the slide uses icons (§8.1 suite) |
| `sections/9-illustration-photography.md` | the slide uses a photo, motif, duotone or halftone |
| `sections/10-data-visualisation.md` | the slide carries a chart, stat circles or bubbles |
| `sections/12-archetypes.md` | the SKILL.md quick-map does not resolve the archetype |
| `sections/13-4-interaction-patterns-interactive-html-de.md` | the deck needs expandable cards or other interaction |
| `sections/14-motion-system-v3-2-the-deck-feels-alive-.md` | motion is full or subtle (skip when motion: off) |
| `sections/14-5-revising-a-delivered-deck.md` | you are revising an already-delivered deck |
"""

# Intro to the hoisted composition block. Real guidance — it says WHY these
# three subsections are in CORE at all — so it is preserved verbatim.
COMPOSITION_INTRO = """These three subsections of §12 are **enforced by verify_deck.py on every
deck** — the composition tripwire and the C1-C7 art-direction checklist.
They are reproduced here verbatim so they load with CORE; the rest of §12
stays in `sections/12-archetypes.md` behind its trigger."""


# The CORE manifest: headings, in CORE's order, taken verbatim from sections/.
# A heading here that no section provides is an error, not a silent omission.
# Adding one is a decision about what every deck pays for — CORE is loaded for
# every deck whether or not the slide needs it.
CORE_MANIFEST = [
    '## 1. Brand essence — read this first',
    '## 2. Canvas, grid & spacing',
    '## 2a. Self-contained file rule (non-negotiable)',
    '## 3. Colour',
    '### 3.1 Primary palette',
    '### 3.2 Secondary palette (the Orange ramp)',
    '### 3.3 Colour roles (from the playbook "Colour Combinations" page — the master role mapping)',
    '### 3.3a Background consistency (do not mix warm and cold whites)',
    '### 3.4 Sanctioned background + dot combinations',
    '### 3.5 Accessibility matrix (text on background)',
    '### 3.6 Tertiary palette (information graphics only)',
    '### 3.7 CSS tokens',
    '### 3.8 Semantic data colours (v4 — the positive/negative cue)',
    '## 4. Typography',
    '### 4.1 Typeface',
    '### 4.2 Weight usage rules (playbook v0.2, verbatim roles)',
    '### 4.3 Type scale',
    '### 4.4 Title highlight (v4 — `.hl`)',
    '### 4.5 Minimum font sizes (v4 — measured law, §15.10)',
    '## 5. The Dot system (shapes & backgrounds)',
    '## 6. Logo',
    '### 6.1 The lockup',
    '### 6.2 Rules',
    '### 6.3 Files',
    '## 7. Slide furniture (headers & footers)',
    '### 7.1 Headline zone (top-left, full width)',
    '### 7.2 Source line (bottom-left)',
    '### 7.3 Footer strip',
    "## 11. Backgrounds by moment (the deck's rhythm)",
    '## 13. Building the HTML deck — conventions & checklist',
    '### 13.1 Skeleton',
    '### 13.2 Mapping an outline to slides',
    "### 13.3 Do / Don't",
    '## 15. Layout & UX laws (v3.6) — enforced geometry',
    '### 15.1 Safe areas & reserved bands',
    '### 15.2 Overlap laws (the collision register)',
    '### 15.3 Alignment laws (the grid is not a suggestion)',
    '### 15.4 Spacing & fit laws',
    '### 15.5 Contrast floor (measured, not assumed)',
    '### 15.6 Vertical balance',
    '### 15.7 Motion UX laws (why the deck never "teleports")',
    '### 15.9 Placement laws (v4): the content edge and media anchoring',
    '### 15.10 Type-size floor (v4)',
    '### 15.8 Enforcement',
    ("## 12.14 / 12.15 / 12.15a — composition (hoisted into CORE)", [
        '### 12.14 Composition guardrails (verified in render QA)',
        '### 12.15 Composition recipes (mined from the template)',
        '### 12.15a Composition checklist (the art-direction pass)',
    ]),
]


def read_sections():
    """{heading: body} plus the ordered section files, from sections/*.md."""
    files = sorted(os.listdir(SECTIONS))
    files = [f for f in files if f.endswith(".md")]
    # _preamble sorts first by name already; keep numeric order for the rest.
    def key(f):
        m = re.match(r"(\d+)", f)
        return (0, 0, f) if f.startswith("_") else (1, int(m.group(1)) if m else 99, f)
    files.sort(key=key)

    blocks, whole = {}, []
    for f in files:
        text = open(os.path.join(SECTIONS, f), encoding="utf-8").read()
        whole.append(text.rstrip() + "\n")
        parts = re.split(r"^(#{2,3} .+)$", text, flags=re.M)
        for i in range(1, len(parts), 2):
            blocks[parts[i].strip()] = parts[i + 1].strip()
    return blocks, "\n".join(whole), files


def render_core(blocks):
    out = [BANNER, CORE_PREAMBLE]
    missing = []
    for entry in CORE_MANIFEST:
        if isinstance(entry, tuple):
            head, children = entry
            out.append(f"{head}\n\n{COMPOSITION_INTRO}\n")
            for c in children:
                if c not in blocks:
                    missing.append(c); continue
                out.append(f"{c}\n\n{blocks[c]}\n")
        else:
            if entry not in blocks:
                missing.append(entry); continue
            out.append(f"{entry}\n\n{blocks[entry]}\n")
    return "\n".join(out).rstrip() + "\n", missing


def render_master(whole):
    return BANNER + whole.rstrip() + "\n"


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--write", action="store_true")
    ap.add_argument("--check", action="store_true")
    args = ap.parse_args()
    if not (args.write or args.check):
        ap.error("pass --write or --check")

    blocks, whole, files = read_sections()
    core, missing = render_core(blocks)
    master = render_master(whole)

    if missing:
        print("MANIFEST ERROR — CORE asks for headings no section provides:", file=sys.stderr)
        for m in missing:
            print(f"  {m}", file=sys.stderr)
        sys.exit(1)

    targets = [(CORE_PATH, core), (MASTER_PATH, master)]

    if args.write:
        for path, text in targets:
            os.makedirs(os.path.dirname(path), exist_ok=True)
            open(path, "w", encoding="utf-8").write(text)
            print(f"wrote {os.path.relpath(path, SKILL)} "
                  f"({len(text):,} chars, ~{len(text)*10//37:,} tokens)")
        print(f"from {len(files)} section files")
        return

    stale = []
    for path, text in targets:
        on_disk = open(path, encoding="utf-8").read() if os.path.isfile(path) else None
        if on_disk != text:
            stale.append((path, on_disk is None))
    if stale:
        print("DOCS STALE — sections/ has moved on and these have not:", file=sys.stderr)
        for path, absent in stale:
            print(f"  {os.path.relpath(path, SKILL)}"
                  f"{' (missing)' if absent else ''}", file=sys.stderr)
        print("\nRun: python3 scripts/build_docs.py --write", file=sys.stderr)
        print("If your edit was to CORE.md or the master, it is in the wrong "
              "file — move it into references/sections/ first.", file=sys.stderr)
        sys.exit(1)
    print(f"DOCS OK — CORE.md and the master both match references/sections/ "
          f"({len(files)} files)")


if __name__ == "__main__":
    main()
