#!/usr/bin/env python3
"""
build_ref_manifest.py — the join between the curated selection and the bank.

Every canon template cites a source slide. This writes the table that makes that
citation checkable: selection page -> master slide number -> family -> target id.

THE JOIN IS FREE. MAP_slides_SELECCION_25.pptx keeps each slide's original
master number as its filename (ppt/slides/slide86.xml is bank slide 86), and
that set matches the "Original" column of SELECCION-25-indice.md exactly. So the
join is derived from two independent sources and cross-checked, rather than
recovered by fuzzy-matching page text — which was the fallback plan and is not
needed.

Page order comes from presentation.xml's sldIdLst, not from sorting filenames:
PowerPoint does not reorder the parts when you reorder the deck.

  python3 canon/_tools/build_ref_manifest.py \
      --pptx ~/Desktop/slides_map/MAP_slides_SELECCION_25.pptx \
      --index ~/Desktop/slides_map/SELECCION-25-indice.md \
      --out ../authoring/canon-ref/manifest.json
"""
import argparse, json, os, re, sys, zipfile

RAG = {"VERDE": "green", "AMARILLO": "amber", "ROJO": "red"}


def selection_order(zf):
    """[(page, master_slide_number)] in presentation order."""
    pres = zf.read("ppt/presentation.xml").decode("utf-8")
    rels = zf.read("ppt/_rels/presentation.xml.rels").decode("utf-8")
    target = dict(re.findall(r'Id="([^"]+)"[^>]*Target="([^"]+)"', rels))
    out = []
    for page, rid in enumerate(re.findall(r'<p:sldId[^>]*r:id="([^"]+)"', pres), 1):
        t = target.get(rid, "")
        m = re.search(r"slide(\d+)\.xml$", t)
        if m:
            out.append((page, int(m.group(1))))
    return out


def index_rows(path):
    """{master_slide: {...}} from the hand-written taxonomy."""
    rows = {}
    for line in open(path, encoding="utf-8"):
        m = re.match(r"\|\s*(\d+)\s*\|\s*([A-H])\s*·\s*(\w+)\s*\|\s*(\d+)\s*\|\s*(.+?)\s*\|\s*(\w+)\s*\|", line)
        if not m:
            continue
        page, fam_letter, fam_name, orig, target, rag = m.groups()
        rows[int(orig)] = {
            "indexPage": int(page),
            "family": f"{fam_letter}-{fam_name.lower()}",
            "targetId": target.strip(),
            "rag": RAG.get(rag.upper(), rag.lower()),
        }
    return rows


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--pptx", required=True)
    ap.add_argument("--index", required=True)
    ap.add_argument("--out", required=True)
    args = ap.parse_args()

    for p in (args.pptx, args.index):
        if not os.path.isfile(p):
            sys.exit(f"not found: {p}")

    with zipfile.ZipFile(args.pptx) as zf:
        order = selection_order(zf)
    idx = index_rows(args.index)

    from_pptx, from_index = {n for _, n in order}, set(idx)
    if from_pptx != from_index:
        print(f"JOIN MISMATCH\n  only in pptx : {sorted(from_pptx - from_index)}"
              f"\n  only in index: {sorted(from_index - from_pptx)}", file=sys.stderr)
        sys.exit(1)

    entries = []
    for page, n in order:
        r = idx[n]
        entries.append({
            "page": page,                       # 1-based page in the selection PDF/PPTX
            "sourceSlide": n,                   # slide number in the 205-slide bank
            "part": f"ppt/slides/slide{n}.xml",
            "family": r["family"],
            "targetId": r["targetId"],
            "rag": r["rag"],
            "canonId": None,                    # filled in as templates are built
        })

    manifest = {
        "$comment": "Generated by canon/_tools/build_ref_manifest.py. The join "
                    "between the curated selection and the bank. page -> the PDF "
                    "page to render as ref.png; sourceSlide -> the number "
                    "measure.py takes. canonId is filled in by hand as each "
                    "template lands.",
        "selection": os.path.basename(args.pptx),
        "index": os.path.basename(args.index),
        "count": len(entries),
        "joinMethod": "pptx part filenames cross-checked against the index's "
                      "Original column; both agree on all 25, no fuzzy matching used",
        "entries": entries,
    }

    os.makedirs(os.path.dirname(os.path.abspath(args.out)) or ".", exist_ok=True)
    with open(args.out, "w", encoding="utf-8") as f:
        f.write(json.dumps(manifest, indent=1, ensure_ascii=False) + "\n")

    byfam = {}
    for e in entries:
        byfam.setdefault(e["family"], []).append(e["rag"])
    print(f"JOIN OK — {len(entries)} slides, both sources agree\n")
    for fam in sorted(byfam):
        rags = byfam[fam]
        print(f"  {fam:16} {len(rags):2}  "
              f"{rags.count('green')} green / {rags.count('amber')} amber")
    print(f"\n-> {args.out}")


if __name__ == "__main__":
    main()
